### ISSUE TITLE
Ask site ids from admin panel

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/Link-child-sites-with-main-site#3]
In admin panel ask for site ids and use it to figure out right table name.

**Comment by Arvind8858** [comment]
My laptop issue have been resolved today. Now need 1 day for complete this issue of this project.

**Comment by Arvind8858** [comment]
Sir I tried many ways to access to childsites posts into one plugin but its not possible because in each subtables post Ids will be match and generate contradiction. If have any idea so please share with me and I can work on the same.

**Comment by rohitmanglik** [comment]
I am travelling right now. Please get in touch with Tarun or Anant for this.

**Comment by Arvind8858** [comment]
I have add a feature to add table prifixes of childsites in shortcode  and it will work well like-
[edugorilla-directory type="" category="" childsite_num="2" db_prefix="wp_2_, wp_2_"]

Now need Little bit issue fix.

**Comment by Arvind8858** [comment]
It have been tested and recommited.
