### ISSUE TITLE
Link item to its listing in Child Site

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/Link-child-sites-with-main-site#4]
When a user will click on an item, he should be redirected to the actual listing page in child site.

**Comment by rohitmanglik** [comment]
Also remove Ajax page.

**Comment by Arvind8858** [comment]
I am working on this. It can take some time due to localhost multisite problems.

**Comment by Arvind8858** [comment]
Have been linked to its indivisual actual listing pages. Need to update codes. Soon will update.

**Comment by Arvind8858** [comment]
Uploaded Updated code.
