### ISSUE TITLE
Inconsistent Files

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/Link-child-sites-with-main-site#5]
Why do we have css.zip and js.zip in the server? We should have ready to install files over here.

**Comment by Arvind8858** [comment]
I have updated all files. Now we can simply download this project in zip format and install it like other plugins.

**Comment by rohitmanglik** [comment]
Kindly test it once and close the issue.

**Comment by Arvind8858** [comment]
You need to copy EduGorilla_Portfolio folder copy and paste in your wordpress plugins folder OR simply make its ZIP file and install it directly from wordpress plugin installer.   
I have updated README.md file about this info.
